apiVersion: v1
kind: ConfigMap
metadata:
  name: fcg-games-config
data:
  #Elasticsearch
  Elasticsearch__Uri: "https://my-elasticsearch-project-d08cf8.es.us-central1.gcp.elastic.cloud:443"
  Elasticsearch__Index: "search-games"
  
  #Jwt
  Jwt__Issuer: "CloudGames"
  Jwt__Audience: "FIAP"
  Jwt__ExpireMinutes: "30"

  #Payments service
  PaymentsApi__Url: "http://payments-api-service"

  #RabbitMQ
  RabbitMQ__Host: "rabbitmq-service"
  rabbitMQ__VirtualHost: "/"