apiVersion: v1
kind: Secret
metadata:
  name: fcg-games-secrets
type: Opaque
data:
  ConnectionStrings__DefaultConnection: "INSERIR_BASE64_AQUI"
  Elasticsearch__ApiKey: "INSERIR_BASE64_AQUI"
  Jwt__Key: "INSERIR_BASE64_AQUI"
  RabbitMQ__Username: "INSERIR_BASE64_AQUI"
  RabbitMQ__Password: "INSERIR_BASE64_AQUI"